### ISSUE TITLE
Inaccurate ground reconstruction in segment-1067626

### ISSUE THREAD

**Issue by xslittlegrass** [PJLab-ADG/neuralsim#12]
I'm following the instruction to reprocess and train the model on session `segment-10676267326664322837_311_180_331_180_with_camera_labels`,  with config [withmask_nolidar.230814.yaml](https://github.com/PJLab-ADG/neuralsim/blob/main/code_single/configs/waymo/streetsurf/withmask_nolidar.230814.yaml). However there are a couple of big holes in the reconstructed ground (see screenshots). The normal and depth priors all look normal though.

I'm wondering whether you have any insights on the cause of this issue?

<img width="684" alt="Screenshot 2023-09-01 at 7 03 06 PM" src="https://github.com/PJLab-ADG/neuralsim/assets/2780075/ecde6a77-0694-4a9e-b507-4c8adcba87d3">
<img width="809" alt="Screenshot 2023-09-01 at 7 03 25 PM" src="https://github.com/PJLab-ADG/neuralsim/assets/2780075/34d585f9-2319-4ceb-b08a-172d8e201e1c">
<img width="869" alt="Screenshot 2023-09-01 at 7 05 36 PM" src="https://github.com/PJLab-ADG/neuralsim/assets/2780075/13ea3f67-cb45-4f5b-b7d9-a416f0c360b9">

**Comment by ventusff** [comment]
Yes, i have the same observation. This is because the monocular normals inferred at certain consecutive frames by Omnidata is sevearly incorrect:
![106762_incorrect_mono_normals](https://github.com/PJLab-ADG/neuralsim/assets/25529198/1ee51a8c-acda-422d-b322-d5821146ef1d)
You can check it yourself by checking the tensorboard (the `coll_normals_gt_pred` entry) and the extracted normals `.jpg` files.

You may want to consider adjusting the weights, such as reducing the weight of 'mono_normals' by a factor of ten and increasing the weight of 'mono_depth' (especially `mono_w_reg`) by the same factor. It will work for this sequence, but will compromise other sequences as the inferred monocular depths cues can also be rough and incorrect :(

**Comment by xslittlegrass** [comment]
Thanks for the explanation!
For the evaluation results in table 1 in the paper (Table 1: Quantitative comparison on selected Waymo Open Dataset sequences), did you hand tuned the weights (or other parameters) for each sequence or use the same parameters as in `configs/waymo/streetsurf` for all sequences?

**Comment by ventusff** [comment]
Under each setting, the same config and weights are applied to all sequences, which are also included in the config yamls released.
