### ISSUE TITLE
What does joint_camlidar and joint_camlidar_equivalent_extr do ?

### ISSUE THREAD

**Issue by andrearama** [PJLab-ADG/neuralsim#22]
Hello, 
thanks for the great project and for releasing the code! 
I have a doubt regarding two flags (for the waymo dataset, used also in StreetSurf). 
What does **joint_camlidar** and **joint_camlidar_equivalent_extr** do ?

In waymo_dataset.py, I see the description:
`joint_camlidar=True, # Joint all cameras and lidars; Set this to [true] if you needs to calibrate cam/lidar extrjoint_camlidar_equivalent_extr=True, # Set to [false] if you needs to calibrate cam/lidar extr
`        

Does that mean that if we set **joint_camlidar** to true, it will refine the extrinsics of the cameras and for the lidars? 
That would be great, but not sure where this would happen, as the only difference that I see when setting the **joint_camlidar**=True or False is how you create the **new_odict** ( `transform=c2v @ dpose `versus `transform=c2w` )

Thanks for your time and availability!

**Comment by Geniussh** [comment]
It's not about pose refinement. When joint_camlidar_equivalent_extr is turned on, it means we acknowledge that `c2w` when the image is captured is different from the `c2w` derived from the ego vehicle's pose, due to the non-zero ego-motion and the lag between pose timestamp and image timestamp. Therefore, it takes into consideration the ego motion and uses the ego-compensated pose, i.e. `c2v @ dpose`, to construct the dataset. Otherwise, we ignore this and simply use the `c2w` when the image is captured.

**Comment by andrearama** [comment]
Thanks for the answer @Geniussh !
Could you please point me on where in the code the poses are being wrapped as pytorch variables?

**Comment by Geniussh** [comment]
It's in the same learnable_params.py I linked above. And you can track it down to the lowest level which leads to nr3d_lib.models.attributes. You can find how the forward pass is defined for the custom TransformRT class, which is what I meant by "wrap" but it's certainly an oversimplified saying. 

In my past projects I just initialized a torch variable with length 6, and with requires_grad=True. 3 for translation and 3 for rotation. I did not impose any constraint on the rotation during training and it also worked. IMHO I guess the author defined such custom libraries here mainly in order to impose SO3 constrain during training.  Maybe I'm wrong.

**Comment by andrearama** [comment]
Thanks for the prompt reply and availability @Geniussh . Really appreciated! 
I guess I can close this issue
