### ISSUE TITLE
Loss is NaN when training StreetSurf

### ISSUE THREAD

**Issue by filick** [PJLab-ADG/neuralsim#4]
Hi,

I tried to train the StreetSurf model on the Waymo-100613 scene but got a NaN loss at the first step. I just downloaded the processed data pack and tried several configs under code_single/configs/waymo/streetsurf/, nothing is modified expect file paths, but all experiments failed the same. I give some screanshots of logs below. I print the detailed loss dict, it seems the rgb loss and mask loss is NaN.

exp using nomask_withlidar.230814.yaml:
![image](https://github.com/PJLab-ADG/neuralsim/assets/8766559/86f34444-19e2-4207-9652-2b0be5fdcead)

exp using withmask_withlidar.230814.yaml:
![image](https://github.com/PJLab-ADG/neuralsim/assets/8766559/a919feaa-7ed2-4978-922d-39c54ea3c1ef)

My environment is Pytorch 2.0.1, cuda 11.8.

Can you take a look? Thanks.

**Comment by ventusff** [comment]
:thinking:  I have never tried on pytorch 2 before. Taking a look now

**Comment by ventusff** [comment]
Hi @filick  It seems that it's because pytorch 2 does not like it when lr gets to exactly zero. This could happen in our current warmup scheduler design.
It should be fixed now (sorry that i accidentally closed this issue). You can `git pull` to update to the latest then `git submodule update --init --recursive` to also update the submodule `nr3d_lib`. Let me know if its fixed :)

**Comment by filick** [comment]
Yes, my training looks good now.Thanks @ventusff , you are fast!
